### PR TITLE
webui: added version and current_mode status

### PR DESCRIPTION
**Pull request by rifsxd**
Screenshot_20241129-150703

### CODE REVIEW

**Comment by KOWX712** [comment]
@rifsxd revert the .bak file

**Comment by rifsxd** [comment]
> @rifsxd revert the .bak file

My bad

**Comment by rifsxd** [comment]
Good to go

**Review by KOWX712 — COMMENTED** [review]
Overall working good, can merge first.

**Comment by backslashxx** [comment]
ill do a squash of the one with the .bak remove, dont update your trees yet

**Comment by backslashxx** [comment]
all good! thanks for the PR

**Pull request merged**
