### PR TITLE
Switch to toybox nproc

### PR DESCRIPTION
**Pull request by bryanyee33**

### CODE REVIEW

**Comment by backslashxx** [comment]
not all has this, you have to design a fallback

**Review by backslashxx — CHANGES_REQUESTED** [review]
not all has this, you have to make it a fallback
image


try playing with like
```
busybox nproc --all 2>/dev/null || toybox nproc --all 2>/dev/null || echo 4
```

**Review by backslashxx — CHANGES_REQUESTED** [review]
I actually did tests on coreutils sort, we do NOT even need to do --parallel, its already parallel by default.
better remove parallel and the nproc thing.

**Comment by bryanyee33** [comment]
Yes, it is actually set to the number of processors available by default:
https://www.gnu.org/software/coreutils/manual/html_node/sort-invocation.html

I'll change it.

**Review by backslashxx — APPROVED** [review]

**Pull request merged**
